### ISSUE TITLE
unable to train/sample using mpiexec on multiple GPUs

### ISSUE THREAD

**Issue by aksy1999** [openai/guided-diffusion#12]
Thanks for providing the code implementation. 

I am able to train and sample model on 1 GPU but facing an issue while using multiple GPUs . 

I am creating multiple process using mpiexec (  tried mpiexec from both OpenMPI and MPICH, having same issue).

Issue: For both sampling and training case, multiple processes are created and model loaded on GPU. But it's not able to sample/train. I see no progress at all. (seems like a deadlock situation). 

Below is the command, I am running for sampling. 

`mpiexec -n 8 python classifier_sample.py --attention_resolutions 32,16,8 --class_cond True --diffusion_steps 1000 --image_size 256 --learn_sigma True --noise_schedule linear --num_channels 256 --num_head_channels 64 --num_res_blocks 2 --resblock_updown True --use_fp16 True --use_scale_shift_norm True --classifier_scale 1.0 --classifier_path "models/256x256_classifier.pt" --model_path "models/256x256_diffusion.pt" --batch_size 1 --num_samples 4 --timestep_respacing 250` 

Problem: It  is getting stuck at <line93, classifier_sample.py> i.e,`all_images.extend([sample.cpu().numpy() for sample in gathered_samples])` 

Below is the command, I am running for training

`mpiexec -n 8 python image_train.py --data_dir ./data_dir --image_size 256 --class_cond False --learn_sigma True --num_channels 256 --num_res_blocks 2 --num_head_channels 64 --attention_resolutions 32,16,8 --dropout 0.1 --diffusion_steps 1000 --noise_schedule linear --use_checkpoint True --use_scale_shift_norm True --resblock_updown True --use_fp16 True --use_new_attention_order True --lr 1e-4 --batch_size 32`

Problem: It is getting stuck in TrainLoop init function... Where distributeDataParallel function is called i.e, 
`self.ddp_model = DDP( self.model, device_ids=[dist_util.dev()], output_device=dist_util.dev(), broadcast_buffers=False, bucket_cap_mb=128, find_unused_parameters=False,)`

I have waited for approx. 24 hours to observe if code proceeds, but it did not. I have tried different approaches also to create multiple process like `python -m torch.distributed.run --nnodes=1 --nproc_per_node=4` and multiprocess.spawn. They were of not much help too. 

With this issue:

A) I request you to if possible please provide the version details of all the dependencies. It will be a great help. Like PyTorch, CUDA, CUDNN, Python, OpenMPI/MPICH, mpi4py and so on.  Possibly it is occurring due to dependency incompatibility. 
I also build PyTorch from source with CUDA 11.2, noticed same issue. 

B) Also, it will be great help to know your insights from training. Did you notice any such behavior? Will you suggest some efficient training strategy for ablation study? 

Below are the dependencies version I am using currently:
conda 4.10.3
Python 3.9.7
PyTorch 1.9.1  (py3.9_cuda11.1_cudnn8.0.5_0)
cudatoolkit   11.1.74
mpich 3.4.2
mpi4py 3.1.1

I am really sorry in case I miss any details.

**Comment by guillaumejs2403** [comment]
Hi, I had the same problem while running the training code. It seems that there is a deadlock with NCCL 2.7.8 [(check here)](https://github.com/pytorch/pytorch/issues/47885). Try changing the backend to gloo. After that I got an error `RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.` [here](https://github.com/openai/guided-diffusion/blob/27c20a8fab9cb472df5d6bdd6c8d11c8f430b924/guided_diffusion/dist_util.py#L83). I still haven't managed to fix it. Any ideas?

python 3.8.11
pytorch 1.9.1
cudatoolkit 10.2.89
mpi4py 3.0.3

**Comment by Kai-0515** [comment]
> thx so much!!!

**Comment by JiamingLiu-Jeremy** [comment]
> Hi, I had the same problem while running the training code. It seems that there is a deadlock with NCCL 2.7.8 [(check here)](https://github.com/pytorch/pytorch/issues/47885). Try using `export NCCL_P2P_DISABLE=1` before using it, it worked for me'
> 
> python 3.8.11 pytorch 1.9.1 cudatoolkit 10.2.89 mpi4py 3.0.3

Thanks for the suggestions. Have you facing the problem during resumeing training, e.g. loading ckpt, optimizer and so forth, when applying multi-gpus.

**Comment by vie131313** [comment]
> Hi, I had the same problem while running the training code. It seems that there is a deadlock with NCCL 2.7.8 [(check here)](https://github.com/pytorch/pytorch/issues/47885). Try using `export NCCL_P2P_DISABLE=1` before using it, it worked for me'
> 
> python 3.8.11 pytorch 1.9.1 cudatoolkit 10.2.89 mpi4py 3.0.3

Thanks for the suggestions. Have you been facing the problem during resumeing training, e.g. loading ckpt, optimizer and so forth, when applying multi-gpus.I found this code only can run again using one process and couldn't work on multi-process when I resume it.Do you know why?Thanks very much!!!
